name: Frontend Deploy (React → Nginx)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Typecheck
        run: npm run typecheck --if-present

      - name: Lint
        run: npm run lint --if-present

      - name: Unit tests (Vitest/Jest)
        run: npm test --if-present -- --ci --watch=false

      - name: Build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: npm run build

      - name: Upload build via rsync
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avz --delete
          path: dist/
          remote_path: ${{ secrets.FRONT_RELEASES_DIR }}/${{ github.sha }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}

      - name: Activate release (symlink switch) + Nginx reload + cleanup
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -euo pipefail
            RELEASES_DIR="${{ secrets.FRONT_RELEASES_DIR }}"
            CURRENT_LINK="${{ secrets.FRONT_CURRENT_LINK }}"
            NEW_REL="${RELEASES_DIR}/${{ github.sha }}"

            mkdir -p "${RELEASES_DIR}"
            [ -d "${NEW_REL}" ] || { echo "Release dir missing"; exit 1; }

            ln -sfn "${NEW_REL}" "${CURRENT_LINK}"

            sudo nginx -t
            sudo systemctl reload nginx

            cd "${RELEASES_DIR}"
            ls -1t | tail -n +4 | xargs -r rm -rf
